### ISSUE TITLE
overlay=PXxPYx deprecated question

### ISSUE THREAD

**Issue by youngjey** [pbs/serverless-its#101]
Just wondering if the overlay will only work in the top left corner now?  I noticed that the PXxPYx values have been removed from the latest README.MD.
removed -  API_URL/<file_path/filename.ext>?overlay=PXxPYx<overlay_img_path>
new - >API_URL/<file_path/filename.ext>?overlay=<overlay_img_path>

Thank you,
John

**Comment by cmac1000** [comment]
Hello @youngjey! You are correct, overlay currently only work in the upper left corner; we changed the behavior in #96 to match the existing behavior of an internal service that we're replacing.

Sorry to surprise you - we actually didn't realize the application had external users yet 🙂 .

We should make it clearer that the API of the application is still pre-1.0, and likely to change further before it stabilizes.
